### ISSUE TITLE
Non Latin characters shouldn't be allowed

### ISSUE THREAD

**Issue by nilsreichardt** [fredeil/email-validator.dart#8]
**Describe the bug :bug:** 
`EmailValidator.validate("ö@gmail.com")` returns true

**To Reproduce**
1. Use any non latin in the address, like `ö`, `🙂`, `ß`
2. Call `EmailValidator.validate(email)`

**Expected behavior**
Regarding to Wikipedia (https://en.wikipedia.org/wiki/Email_address#Local-part) non Latin characters shouldn't be allowed.

**Comment by SvenSchoene** [comment]
I was a bit skeptical of this at first, but I just tested registering a new Gmail-address with an `ö`-character and it's disallowed.

(I was personally invested in checking this, since I have an `ö` in my name, but I'm using `oe` in all my email addresses. Now I remembered why I did that again. :) )

**Comment by fredeil** [comment]
Thanks for reporting this @AndroidNils, I wasn't aware of that. I will research it a bit

**Comment by fredeil** [comment]
They are actually allowed in the newest RFC (see https://tools.ietf.org/html/rfc6532). Can you try passing in false in the `allowInternational` parameter on `Validate` @AndroidNils
